import type { User, Match } from "./types";

export const ME_ID = "u_me";

export const me: User = {
  id: ME_ID,
  displayName: "あなた",
  avatarSeed: "ember",
  major: "情報工学",
  year: 2,
  cards: [
    {
      id: "c_me_1",
      userId: ME_ID,
      category: "hobby",
      title: "写真を撮るのが好き",
      content: "休日はフィルムカメラを持って散歩しています。",
      visibility: "public",
      tags: ["写真", "散歩", "フィルム"],
    },
    {
      id: "c_me_2",
      userId: ME_ID,
      category: "topic",
      title: "最近ハマっている音楽",
      content: "シティポップと、雨の日のlo-fi。",
      visibility: "masked",
      triggerType: "match",
      tags: ["音楽", "シティポップ", "lo-fi"],
    },
    {
      id: "c_me_3",
      userId: ME_ID,
      category: "trouble",
      title: "研究室選びに迷っている",
      content: "AI系か、HCI系か。話せる人がいたら嬉しい。",
      visibility: "conditional",
      triggerType: "chat",
      tags: ["研究室", "AI", "HCI"],
    },
    {
      id: "c_me_4",
      userId: ME_ID,
      category: "value",
      title: "ゆっくり話すのがすき",
      content: "大勢より、ひとりかふたりで深く話したい。",
      visibility: "public",
      tags: ["内向的", "対話"],
    },
  ],
};

export const others: User[] = [
  {
    id: "u_aoi",
    displayName: "あおい",
    avatarSeed: "teal",
    major: "文学部",
    year: 2,
    cards: [
      {
        id: "c_aoi_1",
        userId: "u_aoi",
        category: "hobby",
        title: "古いカメラを集めてる",
        content: "フィルムの粒状感がやっぱり好きで。",
        visibility: "masked",
        triggerType: "match",
        tags: ["写真", "フィルム", "カメラ"],
      },
      {
        id: "c_aoi_2",
        userId: "u_aoi",
        category: "topic",
        title: "最近のプレイリスト",
        content: "雨の日はlo-fiばかり聴いています。",
        visibility: "masked",
        triggerType: "match",
        tags: ["音楽", "lo-fi"],
      },
      {
        id: "c_aoi_3",
        userId: "u_aoi",
        category: "value",
        title: "静かな場所がすき",
        content: "図書館の奥のソファが定位置。",
        visibility: "public",
        tags: ["内向的", "読書"],
      },
      {
        id: "c_aoi_4",
        userId: "u_aoi",
        category: "current",
        title: "短編小説を書いている",
        content: "誰にも見せてないけど、毎週少しずつ。",
        visibility: "conditional",
        triggerType: "chat",
        tags: ["創作", "小説"],
      },
    ],
  },
  {
    id: "u_ren",
    displayName: "れん",
    avatarSeed: "coral",
    major: "経済学部",
    year: 1,
    cards: [
      {
        id: "c_ren_1",
        userId: "u_ren",
        category: "hobby",
        title: "サウナと銭湯めぐり",
        content: "市内の銭湯は半分くらい回りました。",
        visibility: "public",
        tags: ["サウナ", "銭湯"],
      },
      {
        id: "c_ren_2",
        userId: "u_ren",
        category: "trouble",
        title: "ひとりでごはんが寂しい",
        content: "食堂でいつもぼっちです…",
        visibility: "masked",
        triggerType: "match",
        tags: ["ぼっち飯", "食堂"],
      },
      {
        id: "c_ren_3",
        userId: "u_ren",
        category: "topic",
        title: "マンガの話したい",
        content: "特にスローライフ系と、青年誌。",
        visibility: "public",
        tags: ["マンガ", "読書"],
      },
    ],
  },
  {
    id: "u_hina",
    displayName: "ひな",
    avatarSeed: "sand",
    major: "建築",
    year: 2,
    cards: [
      {
        id: "c_hina_1",
        userId: "u_hina",
        category: "hobby",
        title: "建築の散歩が趣味",
        content: "街を歩きながら窓のディテールを眺めます。",
        visibility: "public",
        tags: ["散歩", "建築"],
      },
      {
        id: "c_hina_2",
        userId: "u_hina",
        category: "value",
        title: "ひとり時間を大切にしたい",
        content: "内向的なので無理しない関係がいい。",
        visibility: "public",
        tags: ["内向的"],
      },
      {
        id: "c_hina_3",
        userId: "u_hina",
        category: "topic",
        title: "HCIに興味がある",
        content: "空間とインターフェースの境目が好き。",
        visibility: "masked",
        triggerType: "match",
        tags: ["HCI", "研究室"],
      },
    ],
  },
];

export const seedUsers: User[] = [me, ...others];

/** Pre-computed matches for demo (mock of proximity + tag overlap). */
export const seedMatches: Match[] = [
  {
    id: "m_aoi",
    userA: ME_ID,
    userB: "u_aoi",
    score: 0.82,
    commonTags: ["写真", "フィルム", "音楽", "lo-fi", "内向的"],
    metAt: new Date().toISOString(),
    locationHash: "lib-3f",
    status: "new",
  },
  {
    id: "m_hina",
    userA: ME_ID,
    userB: "u_hina",
    score: 0.48,
    commonTags: ["散歩", "内向的", "HCI", "研究室"],
    metAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    locationHash: "cafe-central",
    status: "new",
  },
  {
    id: "m_ren",
    userA: ME_ID,
    userB: "u_ren",
    score: 0.22,
    commonTags: ["読書"],
    metAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    locationHash: "canteen-1f",
    status: "new",
  },
];
